services:
  frontend:
    image: ghcr.io/aonoexercist/next-gin-frontend:latest
    expose:
      - "3000"
    env_file:
      - .env
    restart: always

  backend:
    image: ghcr.io/aonoexercist/gin-api-backend:latest
    expose:
      - "8080"
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine # Or mysql:8.0
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  db_data: # This ensures your database data isn't lost when the container stops