services:
  frontend:
    image: ghcr.io/aonoexercist/next-gin-frontend:latest
    restart: always

  backend:
    image: ghcr.io/aonoexercist/gin-api-backend:latest
    restart: always
    environment:
      - DB_URL=your_db_connection_string

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # Open for HTTP
      - "443:443" # Open for HTTPS later
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always