apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
        - name: nextjs
          image: ghcr.io/aonoexercist/next-gin-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://gin-backend:8080
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              value: 305742023400-1eor04p99qkbs5o1q0d3ggkg97jqour2.apps.googleusercontent.com