apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-backend
  template:
    metadata:
      labels:
        app: gin-backend
    spec:
      containers:
        - name: gin-backend
          image: ghcr.io/aonoexercist/gin-api-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: db