apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-backend
  template:
    metadata:
      labels:
        app: gin-backend
    spec:
      containers:
        - name: gin-backend
          image: ghcr.io/aonoexercist/gin-api-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: db
            - name: DB_PORT
              value: "5432"
            - name: JWT_SECRET
              value: COKwHA1gqG6DXyOHHKzxPxOZk6tDA7pToJuG5qVDGEo
            - name: GOOGLE_CLIENT_ID
              value: 305742023400-1eor04p99qkbs5o1q0d3ggkg97jqour2.apps.googleusercontent.com